diymarket/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import PasswordChangeDoneView,PasswordChangeView
from market import views

urlpatterns = [
    path('', views.home, name='home'),
    path('admin/', admin.site.urls),
    path('market/', include('market.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('profile', views.OderListofUser.as_view(), name='user-profile'),
    path('password_change/',
         PasswordChangeView.as_view(template_name="registration/change_password.html"),
         name='password_change'),
    path('password_change/done/',
         PasswordChangeDoneView.as_view(template_name="registration/password_change_done.html"),
         name='password_change_done'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

market/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='market-index'),
    path('order/get', views.get_orders, name='get-orders'),
    path('order/create/', views.OrderCreate.as_view(), name='order-create'),
    path('order/delete/<str:pk>', views.OrderDelete.as_view(), name='order-delete'),
    path('matching/<str:type>', views.MatchbyUser.as_view(), name='matching-list-view'),
    path('matching/create/', views.OrderMatchingCreate.as_view(), name='matching-create'),
    path('matching/delete/<str:type>/<str:pk>/<str:st>', views.OrderMatchingDelete.as_view(), name='matching-delete'),
]

market/models.py
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings
import uuid

# Create your models here.

class Order(models.Model):
    """Model representing an order"""
    id = models.UUIDField(primary_key=True, default=uuid.uuid4)
    type = models.CharField(
        max_length=1,
        choices=settings.TYPE_CHOICE,
        null=True,
        help_text='Buy or Sell order',
    )
    location = models.CharField(
        max_length=1,
        choices=settings.LOCATION_CHOICE,
        default='3',
        help_text='Enter the location of order'
    )
    item_id = models.CharField(max_length=100, help_text='Enter the UniqueName of item')
    quality = models.CharField(
        max_length=1,
        choices=settings.QUALITY_CHOICE,
        default='0',
        help_text='Enter the quality of item'
    )
    price = models.PositiveIntegerField(default=0, help_text='Price of item')
    amount = models.PositiveIntegerField(default=0, help_text='Number of item')
    username = models.ForeignKey(User, to_field="username", on_delete=models.SET_NULL, null=True)

    def __str__(self):
        """String for representing the Model object."""
        return f'{self.id}'

class OrderMatching(models.Model):
    """Model representing an order matching"""
    id = models.UUIDField(primary_key=True, default=uuid.uuid4)
    order = models.ForeignKey('Order', on_delete=models.SET_NULL, null=True)
    amount = models.PositiveIntegerField(default=0, help_text='Number of item')
    username = models.ForeignKey(User, to_field="username", on_delete=models.SET_NULL, null=True)
    status = models.CharField(
        max_length=1,
        choices=settings.STATUS_CHOICE,
        default='0',
        help_text='Status of order',
    )

    def __str__(self):
        """String for representing the Model object."""
        return f'{self.order}'

market/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.models import User
from django.views import generic
from django.views.generic.edit import CreateView, DeleteView
from django.urls import reverse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse
from django.conf import settings
from django.db.models import Q

from .models import Order, OrderMatching

# Create your views here.

def home(request):
    """View function for home page of site."""
    num_sell_orders = Order.objects.filter(type__exact='s').count()
    num_buy_orders = Order.objects.filter(type__exact='b').count()
    num_users = User.objects.count() - 1

    context = {
        'num_sell_orders': num_sell_orders,
        'num_buy_orders': num_buy_orders,
        'num_users': num_users,
    }
    context['LocationDetail'] = {}
    for (c, name) in settings.LOCATION_CHOICE:
        obj = Order.objects.filter(location__exact=c)
        context['LocationDetail'][name] = {
            'num_sell_orders': obj.filter(type__exact='s').count(),
            'num_buy_orders': obj.filter(type__exact='b').count(),
        }
    return render(request, 'home.html', context=context)

def index(request):
    """View function for market page of site."""
    # Render the HTML template index.html with the data in the context variable
    return render(request, 'index.html')

def get_orders(request):
    '''
    Get all Orders which have match TYPE and LOCATION
    '''
    # Get type and location from resquest
    type = request.GET.get('type', None)  
    location = request.GET.get('location', None)  

    if (type and location):
        # Find all object in data
        result = list(
            Order.objects.filter(
                type=type, location=location
            ).order_by('price').values()
        )
        if result:
            return JsonResponse({
                "status": "success",
                "result": result,
            })

    return JsonResponse({
        "status": "No items"
    })

# User Profile
class OderListofUser(LoginRequiredMixin, generic.ListView):
    """
    User profile view, list of orders create by User
    """
    model = Order
    # paginate_by = 5
    template_name ='market/user_profile.html'

    def get_object(self):
        return self.request.user

    def get_queryset(self):
        """
        Return list of Order objects created by User
        """
        target_user = get_object_or_404(User, username=self.request.user)
        return Order.objects.filter(username=target_user)
        
    def get_context_data(self, **kwargs):
        """
        Add User to context so they can be displayed in the template
        """
        # Call the base implementation first to get a context
        context = super(OderListofUser, self).get_context_data(**kwargs)
        # Get the user object from the "username" URL parameter and add it to the context
        user = get_object_or_404(User, username=self.request.user)
        if user:
            context['username'] = user.username
        return context

class MatchbyUser(LoginRequiredMixin, generic.ListView):
    """
    User profile view, list of orders create by User
    """
    model = OrderMatching
    template_name ='market/order_matching.html'
    ordering = ['username']

    def get_object(self):
        return self.request.user

    def get_queryset(self):
        """
        Return list of OrderMatching objects created by User
        """
        # type = 's' if (self.kwargs["type"]=='buy') else 'b'
        target_user = get_object_or_404(User, username=self.request.user)
        return OrderMatching.objects.filter(
                Q(username=target_user) |
                Q(order__username=target_user)
            ).filter(order__type__isnull=False)#.filter(order__type=type)

    def get_context_data(self, **kwargs):
        """
        Add User to context so they can be displayed in the template
        """
        # Call the base implementation first to get a context
        context = super(MatchbyUser, self).get_context_data(**kwargs)
        # Get the user object from the "username" URL parameter and add it to the context
        user = get_object_or_404(User, username=self.request.user)
        if user:
            context['username'] = user.username
        context['trader_type'] = 'bán' if (self.kwargs["type"][0]=='b') else 'mua'
        return context


# Order create, delete
class OrderCreate(LoginRequiredMixin, CreateView):
    model = Order
    fields = ['type', 'location', 'item_id', 'quality', 'price', 'amount']

    def form_valid(self, form):
        form.instance.username = self.request.user
        return super(OrderCreate, self).form_valid(form)

    def get_success_url(self):
        """
        Back to the market home page
        """
        return reverse('user-profile')

class OrderDelete(LoginRequiredMixin, DeleteView):
    model = Order

    def get_queryset(self):
        """
        Return list of order objects created by current User
        """
        username = get_object_or_404(User, username=self.request.user)
        return Order.objects.filter(username=username)

    def get_success_url(self):
        """
        Back to the market home page
        """
        return reverse('user-profile')


# Order_Matching create, delete
class OrderMatchingCreate(LoginRequiredMixin, CreateView):
    model = OrderMatching
    fields = ['order', 'amount']

    def form_valid(self, form):
        form.instance.username = self.request.user
        return super(OrderMatchingCreate, self).form_valid(form)

    def get_success_url(self):
        """
        Back to the market home page
        """
        # Minus the amount in Order by the amount match
        order_obj = Order.objects.get(id=self.object.order.id)
        order_obj.amount = order_obj.amount - self.object.amount
        order_obj.save()
        return reverse('market-index')

class OrderMatchingDelete(LoginRequiredMixin, DeleteView):
    model = OrderMatching

    def get_queryset(self):
        """
        Return list of order objects created by current User
        or the objects has order.username is current User
        """
        target_user = get_object_or_404(User, username=self.request.user)
        return OrderMatching.objects.filter(
                Q(username=target_user) |
                Q(order__username=target_user)
            ).filter(order__type__isnull=False)

    def get_success_url(self):
        """
        Back to the user page
        """
        # If cancel, return the amount minus when create
        order_obj = Order.objects.get(id=self.object.order.id)
        if (self.kwargs['st'] == 'cancel'):
            order_obj.amount = order_obj.amount + self.object.amount
            order_obj.save()
        # Delete order when amount become 0
        else:
            if (order_obj.amount==0):
                order_obj.delete()

        return reverse('matching-list-view', kwargs={'type': self.kwargs['type']})

market/templates/market/order_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Are you Sure</h1>

<form method="post" action="">
  {% csrf_token %}
  <input class="btn btn-danger" type="submit" value="Yes, Delete!" />
</form>

{% endblock %}

market/templates/market/order_form.html
{% extends "base_generic.html" %} {% block content %}
<form action="" method="post">
  {% csrf_token %}
  <table id="TableForm" style="width: 80%;">
    <tbody>
      <tr>
        <th><label for="id_type">Bạn muốn:</label></th>
        <td>
          <select name="type" required="" id="id_type" class="dropdown">
            <option value="" selected="">---------</option>
            <option value="b">Mua</option>
            <option value="s">Bán</option>
          </select>
        </td>
      </tr>
      <tr>
        <th><label for="id_location">Ở:</label></th>
        <td>
          <select name="location" id="id_location" class="dropdown">
            <option value="0">Thetford</option>
            <option value="1">Martlock</option>
            <option value="2">Bridgewatch</option>
            <option value="3" selected="">Lymhurst</option>
            <option value="4">Fort Sterling</option>
            <option value="5">Caerleon</option>
          </select>
        </td>
      </tr>
      <tr>
        <th><label for="id_item_id">Tên item:</label></th>
        <td>
          <input
            class="text-input"
            type="text"
            name="itemName"
            v-model="itemName"
            placeholder="Nhập tên item (tối thiểu 3 kí tự)"
            @keyup="displayMatch(itemName)"
            :disabled="itemID!==''"
          />
          <input
            v-show="false"
            type="text"
            name="item_id"
            required=""
            id="id_item_id"
            v-model="itemID"
          />
      </tr>
      <tr>
        <th></th>
        <td>
          <table class="table-of-items" style="width: 100%; margin-top: 0;">
            <colgroup>
              <col span="1" style="width: 20%;">
              <col span="1" style="width: 80%;">
            </colgroup>
            <tbody>
              <tr>
                <th v-if="itemsList.length > maxNumShow">Tier</th>
                <th v-else>Item</th>
                <th>Tên</th>
              </tr>
              <tr v-for="(item, index) in itemsList" class="item-selector" @click="select(item)">
                <td v-if="itemsList.length > maxNumShow">[[ uniNameToTier(item.UniqueName) ]]</td>
                <td v-else><img class="thumbnail" :src="imgAPI + item.UniqueName" :alt="uniNameToTier(item.UniqueName)"/></td>
                <td>[[ item.LocalizedNames ]]</td>
              </tr>
            </tbody>
          </table>
        </td>
      </tr>
      <tr v-show="doneSelect">
        <th><label for="id_quality">Chất lượng:</label></th>
        <td>
          <select name="quality" id="id_quality" class="dropdown">
            <option value="0" selected>Normal</option>
            <option value="1">Good</option>
            <option value="2">Outstanding</option>
            <option value="3">Excellent</option>
            <option value="4">Masterpiece</option>
          </select>
        </td>
      </tr>
      <tr v-show="doneSelect">
        <th><label for="id_price">Giá đặt:</label></th>
        <td>
          <input
            class="dropdown"
            type="number"
            name="price"
            value="0"
            min="0"
            required=""
            id="id_price"
            v-model="price"
          />
        </td>
      </tr>
      <tr v-show="doneSelect">
        <th><label for="id_amount">Số lượng:</label></th>
        <td>
          <input
            class="dropdown"
            type="number"
            name="amount"
            value="0"
            min="0"
            required=""
            id="id_amount"
            v-model="amount"
          />
        </td>
      </tr>
      <tr v-show="doneSelect">
        <th>Tổng cộng:</th>
        <td>[[ total ]]</td>
      </tr>
    </tbody>
  </table>
  <input class="btn btn-outline-primary submit-button" type="submit" value="Xác nhận" />
</form>

<script type="text/javascript">
  const api = 'https://gist.githubusercontent.com/deathvn/d9aeac05ea26bfd12688bfca3581be8b/raw/ffe34a985b6612f436946ea54e5b85011840b9ec/albion-item.json';
  const AlbionItems = [];
  fetch(api).then(res => res.json()).then(function(x) {
    x.forEach(function(el) {
      if (!el.UniqueName.includes('NONTRADABLE')) {
        AlbionItems.push(el);
      }
    });
    // AlbionItems.sort((firstEl, secondEl) => (firstEl.UniqueName - secondEl.UniqueName));
  });

  const data = {
    imgAPI: 'https://render.albiononline.com/v1/item/',
    maxNumShow: 8,
    price: 0,
    amount: 1,
    itemName: '',
    itemID: '',
    doneSelect: false,
    itemsList: [],
  };

  var pageHome = new Vue({
    el : '#TableForm',
    delimiters: ['[[', ']]'],
    data: data,
    methods : {
      find(word) {
        const pattern = word.toLowerCase();
        const result = AlbionItems.filter(function(x) {
          const has_pattern = x.LocalizedNames.toLowerCase().includes(pattern);
          const has_Tier = (x.UniqueName[0] === 'T');
          return has_pattern && has_Tier;
        });
        return result;
      },
      displayMatch(phrase) {
        if (phrase.length >= 3) {
          const matchPlace = this.find(phrase);
          data.itemsList = matchPlace;
        } else {
          data.itemsList = [];
        }
      },
      uniNameToTier(uniName) {
        let enchantment;
        if (uniName.includes('@')) {
          enchantment = uniName.split('@').pop();
        } else {
          enchantment = '0';
        }
        const tier = uniName.substring(1, 2);
        return (tier === 'R') ? tier : `${tier}.${enchantment}`;
      },
      select(item) {
        data.itemsList = [item];
        data.itemID = item.UniqueName;
        data.doneSelect = true;
      },
    },
    computed: {
      total() {
        const formatter = new Intl.NumberFormat('en-US', {
          style: 'currency',
          currency: 'USD',
          minimumFractionDigits: 0,
          // These options are needed to round to whole numbers if that's what you want.
          //minimumFractionDigits: 0, // (this suffices for whole numbers, but will print 2500.10 as $2,500.1)
          //maximumFractionDigits: 0, // (causes 2500.99 to be printed as $2,501)
        });
        return formatter.format(data.price*data.amount);
      }
    }
  });
</script>
{% endblock %}

market/templates/market/order_matching.html
{% extends "base_generic.html" %}

{% block content %}
<h1>{{ username }}</h1>
<p>Danh sách các lệnh
  {% if trader_type == 'mua' %}
    bán
  {% else %}
    mua
  {% endif %}
  đã khớp của bạn. Vui lòng liên hệ trong game để trade.
  <ul>
    <li>Bấm <strong>Hoàn thành</strong> để xác nhận trade thành công.</li>
    <li>Bấm <strong>Hủy</strong> để hủy bỏ giao dịch hoặc trade thất bại.</li>
  </ul>
</p>

<div id="ListOfOrder" v-if="isLoaded">
  <table class="table-of-items" style="width: 100%">
    <colgroup is="table-colgroup"></colgroup>
    <tbody>
      <tr>
        <th>Vị trí</th>
        <th>Item</th>
        <th>Tên</th>
        <th>Chất lượng</th>
        <th>Giá</th>
        <th>Số lượng</th>
        <th>Người {{ trader_type }}</th>
      </tr>
      {% for match in ordermatching_list %}
      <tr is="row-item"
        trader_type="{{trader_type}}"
        id="{{ match.id }}"
        rowid="match-{{ forloop.counter0 }}"
        type="{{ match.order.type }}"
        location="{{ match.order.location }}"
        item_id="{{ match.order.item_id }}"
        quality="{{ match.order.quality }}"
        price="{{ match.order.price }}"
        amount="{{ match.amount }}"
        user={% if match.order.username|stringformat:"s" == username %}"{{ match.username }}"{% else %}"{{ match.order.username }}"{% endif %}
        ismyorder={% if match.order.username|stringformat:"s" == username %}"True"{% else %}"False"{% endif %}
      ></tr>
      [[ calc_silver(
          {% if match.order.username|stringformat:"s" == username %}"{{ match.username }}"{% else %}"{{ match.order.username }}"{% endif %},
          "{{match.order.price}}",
          "{{match.amount}}",
          "{{trader_type}}", "{{ match.order.type }}",
          {% if match.order.username|stringformat:"s" == username %}"True"{% else %}"False"{% endif %}) ]]
      {% endfor %}
    </tbody>
  </table>

  <h2>
    {% if trader_type == 'mua' %}
      Bạn sẽ nhận được từ
    {% else %}
      Bạn cần phải trả cho
    {% endif %}
  </h2>
  <ul v-show="(silver_dict_key.length !== 0)">
    <li v-for="key in silver_dict_key">
      [[ key ]]: [[ get_silver_dict_value(key) ]]
    </li>
  </ul>
</div>

<script type="text/javascript">
  function itemIdToName(item_id) {
    return data.AlbionItems.find(el => el.UniqueName === item_id)['LocalizedNames'];
  }
  
  const TYPE_CHOICE = {
    'b': 'Buy',
    's': 'Sell'
  };
  const LOCATION_CHOICE = {
    '0': 'Thetford',
    '1': 'Martlock',
    '2': 'Bridgewatch',
    '3': 'Lymhurst',
    '4': 'Fort Sterling',
    '5': 'Caerleon'
  };
  const QUALITY_CHOICE = {
    '0': 'Normal',
    '1': 'Good',
    '2': 'Outstanding',
    '3': 'Excellent',
    '4': 'Masterpiece'
  };
  
  Vue.component('table-colgroup', {
    template: `
      <colgroup>
        <col span="1" style="width: 15%;">
        <col span="1" style="width: 15%;">
        <col span="1" style="width: 30%;">
        <col span="1" style="width: 10%;">
        <col span="1" style="width: 15%;">
        <col span="1" style="width: 10%;">
        <col span="1" style="width: 5%;">
      </colgroup>
    `
  });
  
  Vue.component('row-item', {
    delimiters: ['[[', ']]'],
    props: ["rowid", "type", "location", "item_id", "quality", "price", "amount", "user", "id", "ismyorder", "trader_type"],
    data: function () {
      const traderType = this.trader_type=='mua' ? 'b' : 's';
      const sameTradeType = this.type==traderType;
      const isMyOrder = Boolean(this.ismyorder=='False');
      const is_show = isMyOrder ^ !sameTradeType;
      const enTraderType = traderType=='mua'? 'sell' : 'buy';
      return {
        order_type: TYPE_CHOICE[this.type],
        order_location: LOCATION_CHOICE[this.location],
        item_img_src: `${data.imgAPI}${this.item_id}`,
        item_name: itemIdToName(this.item_id),
        action_link: `/market/matching/delete/${enTraderType}/${this.id}/`,
        is_show: is_show
      }
    },
    template: `
      <tr :id="rowid" v-show="is_show">
        <td class="location">[[ order_location ]]</td>
        <td class="item_img"><img class="thumbnail" :src="item_img_src" :alt="item_id"/></td>
        <td class="item_id">[[ item_name ]]</td>
        <td class="item_id">[[ QUALITY_CHOICE[quality] ]]</td>
        <td class="price">[[ price ]]</td>
        <td class="amount">[[ amount ]]</td>
        <td class="amount">[[ user ]]</td>
        <td>
          <form method="POST" :action="action_link + 'cancel'">
            {% csrf_token %}<input class="btn btn-outline-success" type="submit" value="Hoàn thành">
          </form>
        </td>
        <td>
          <form method="POST" :action="action_link + 'cancel'">
            {% csrf_token %}<input class="btn btn-outline-danger" type="submit" value="Hủy">
          </form>
        </td>
      </tr>
      `
  });
  
</script>

<script type="text/javascript">
  const api = 'https://gist.githubusercontent.com/deathvn/d9aeac05ea26bfd12688bfca3581be8b/raw/ffe34a985b6612f436946ea54e5b85011840b9ec/albion-item.json';
  const AlbionItems = [];
  fetch(api).then(res => res.json()).then(x => AlbionItems.push(...x));
  const data = {
    imgAPI: 'https://render.albiononline.com/v1/item/',
    AlbionItems: AlbionItems,
    silver: {}
  }

  var pageHome = new Vue({
    el : '#ListOfOrder',
    components: ['row-item', 'table-colgroup'],
    delimiters: ['[[', ']]'],
    data: data,
    methods : {
      get_silver_dict_value(key) {
        const formatter = new Intl.NumberFormat('en-US', {
          style: 'currency',
          currency: 'USD',
          minimumFractionDigits: 0,
        });
        return formatter.format(data.silver[key]);
      },
      calc_silver(username, price, amount, trader_type, type, ismyorder) {
        const traderType = trader_type=='mua' ? 'b' : 's';
        const sameTradeType = (type==traderType);
        const isMyOrder = Boolean(ismyorder=='False');
        const is_show = isMyOrder ^ !sameTradeType;
        if (is_show) {
          if (data.silver[username] === undefined) {
            data.silver[username] = 0;
          }
          data.silver[username] += price*amount;
        }
      }
    },
    computed: {
      isLoaded() {
        return (data.AlbionItems.length !== 0)
      },
      silver_dict_key() {
        keys = Object.keys(data.silver);
        return keys;
      }
    }
  });
</script>

{% endblock %}

market/templates/market/user_profile.html
{% extends "base_generic.html" %}

{% block content %}
<h1>{{ username }}</h1>
<h2>Lệnh đã khớp</h2>
<ul>
  <li><a href="{% url 'matching-list-view' 'sell' %}">Lệnh bán đã khớp</a></li>
  <li><a href="{% url 'matching-list-view' 'buy' %}">Lệnh mua đã khớp</a></li>
</ul>
</br>

{% if order_list %}
<div id="ListOfOrder" v-if="isLoaded">
  <h2>Lệnh bán còn chờ</h2>
  <table class="table-of-items" style="width: 100%">
    <colgroup is="table-colgroup"></colgroup>
    <tbody>
      <tr is="table-title"></tr>
      {% for order in order_list %}   
      <tr is="row-item"
        gettype="s"
        id="{{ order.id }}"
        rowid="order-{{ forloop.counter0 }}"
        type="{{ order.type }}"
        location="{{ order.location }}"
        item_id="{{ order.item_id }}"
        quality="{{ order.quality }}"
        price="{{ order.price }}"
        amount="{{ order.amount }}"
      ></tr>
      {% endfor %}
    </tbody>
  </table>

  <br/>
  <h2>Lệnh mua còn chờ</h2>
  <table class="table-of-items" style="width: 100%">
    <colgroup is="table-colgroup"></colgroup>
    <tbody>
      <tr is="table-title"></tr>
      {% for order in order_list %}   
      <tr is="row-item"
        gettype="b"
        id="{{ order.id }}"
        rowid="order-{{ forloop.counter0 }}"
        type="{{ order.type }}"
        location="{{ order.location }}"
        item_id="{{ order.item_id }}"
        quality="{{ order.quality }}"
        price="{{ order.price }}"
        amount="{{ order.amount }}"
      ></tr>
      {% endfor %}
    </tbody>
  </table>
</div>

<script type="text/javascript">
function itemIdToName(item_id) {
  return data.AlbionItems.find(el => el.UniqueName === item_id)['LocalizedNames'];
}

const TYPE_CHOICE = {
  'b': 'Buy',
  's': 'Sell'
};
const LOCATION_CHOICE = {
  '0': 'Thetford',
  '1': 'Martlock',
  '2': 'Bridgewatch',
  '3': 'Lymhurst',
  '4': 'Fort Sterling',
  '5': 'Caerleon'
};

Vue.component('table-colgroup', {
  template: `
    <colgroup>
      <col span="1" style="width: 15%;">
      <col span="1" style="width: 15%;">
      <col span="1" style="width: 30%;">
      <col span="1" style="width: 10%;">
      <col span="1" style="width: 15%;">
      <col span="1" style="width: 10%;">
      <col span="1" style="width: 5%;">
    </colgroup>
  `
});

Vue.component('table-title', {
  template: `
    <tr>
      <th>Vị trí</th>
      <th>Item</th>
      <th>Tên</th>
      <th>Chất lượng</th>
      <th>Giá</th>
      <th>Số lượng</th>
    </tr>
  `
});

Vue.component('row-item', {
  delimiters: ['[[', ']]'],
  props: ["gettype", "rowid", "type", "location", "item_id", "quality", "price", "amount", "id"],
  data: function () {
    return {
      order_type: TYPE_CHOICE[this.type],
      order_location: LOCATION_CHOICE[this.location],
      item_img_src: `${data.imgAPI}${this.item_id}`,
      item_name: itemIdToName(this.item_id),
      action_link: `/market/order/delete/${this.id}`
    }
  },
  template: `
    <tr :id="rowid" v-if="gettype===type">
      <td class="location">[[ order_location ]]</td>
      <td class="item_img"><img class="thumbnail" :src="item_img_src" :alt="item_id"/></td>
      <td class="item_id">[[ item_name ]]</td>
      <td class="item_id">[[ QUALITY_CHOICE[quality] ]]</td>
      <td class="price">[[ price ]]</td>
      <td class="amount">[[ amount ]]</td>
      <td>
        <form method="POST" :action="action_link">
          {% csrf_token %}<input class="btn btn-outline-danger" type="submit" value="Hủy">
        </form>
      </td>
    </tr>
    `
});

</script>

<script type="text/javascript">
  const api = 'https://gist.githubusercontent.com/deathvn/d9aeac05ea26bfd12688bfca3581be8b/raw/ffe34a985b6612f436946ea54e5b85011840b9ec/albion-item.json';
  const AlbionItems = [];
  fetch(api).then(res => res.json()).then(x => AlbionItems.push(...x));
  const data = {
    imgAPI: 'https://render.albiononline.com/v1/item/',
    AlbionItems: AlbionItems
  }

  const QUALITY_CHOICE = {
    '0': 'Normal',
    '1': 'Good',
    '2': 'Outstanding',
    '3': 'Excellent',
    '4': 'Masterpiece'
  }

  var pageHome = new Vue({
    el : '#ListOfOrder',
    components: ['row-item', 'table-colgroup', 'table-title'],
    delimiters: ['[[', ']]'],
    data: data,
    methods : {},
    computed: {
      isLoaded() {
        return (data.AlbionItems.length !== 0)
      }
    }
  });
</script>

{% else %}
  <p class='text-muted'>
    Tài khoản này chưa đặt lệnh Mua/Bán nào
    <span style="white-space: nowrap;">ヘ(￣ω￣ヘ)</span>
  </p>
{% endif %}

{% endblock %}